### ISSUE TITLE
Balance looks like it's not correct 

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus#14]
From the transactions, my wallet should have 2860.5785761719951201596648 SC but `balance` returns `32374.6247261991597832313192 SC`

**Comment by lukechampine** [comment]
From the log you shared, it looks like this is related to file contract handling. Need to investigate this more.

**Comment by jkawamoto** [comment]
I remember the contract format `us` makes is different from the one `siad` makes. I'm not sure if it relates to this, though.

**Comment by jkawamoto** [comment]
In v0.8.4, `split` command looks like it shows the correct balance but `balance` command still shows a wrong one.

**Comment by jkawamoto** [comment]
Looks like we get "transaction spends a nonexisting siacoin output" error even if the wallet doesn't have sufficient fund, although it should return "insufficient fund" error instead. 
I'm wondering if the forming contract method also uses a wrong balance.
