### ISSUE TITLE
Couldn't initialize walrus server: cannot upgrade database for Foundation hardfork after activation height

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus#17]
We got this error. How can we resolve this?

**Comment by lukechampine** [comment]
This happens if your node was on the old chain when the hardfork activated. Ensure that you're using the latest version, then resync your consensus.db.

**Comment by jkawamoto** [comment]
I see. So we need to remove `consensus.db` and restart the server.

Btw, we're using muse v0.6.4. It looks like it depends on shard v0.3.5, which depends on Sia v1.5.0. Is that okay, or do we need to update shard?

**Comment by lukechampine** [comment]
Ah, that might be dragging the dependencies down. I've updated `shard` accordingly and tagged muse v0.6.5.

**Comment by jkawamoto** [comment]
Thanks for updating `shard` and `muse`. After upgrading them, I removed `consensus.db` and restarted the server.

But, the block height goes wrong.
```
$ curl http://localhost:9480/height
325399
```
After the first synchronization, will the height be fixed?

**Comment by lukechampine** [comment]
Hmm. I think I see the problem. When you restarted the server, it tried to resubscribe from the last known block. But the last known block wasn't in the new `consensus.db`, so it wiped everything and started over from genesis. But the "wipe everything" code is incomplete -- [it only wipes the CCID](https://github.com/lukechampine/shard/blob/9b23cfed2c9e1ff2765a8651b4bd044afee04c29/relay.go#L93).

I've pushed a commit that should fix this: https://github.com/lukechampine/shard/commit/d271a1d63374e82dc87ea893a21c9978d3583d90

**Comment by jkawamoto** [comment]
Thanks. The height issue and "Couldn't initialize walrus server" error are solved.

Could you release new versions of shard and muse?

**Comment by lukechampine** [comment]
Ok, I've released updated versions of `shard`, `muse`, and `walrus`. Hopefully everything works now 😅

**Comment by jkawamoto** [comment]
Thanks a lot! I'll close this issue.
