### ISSUE TITLE
can't connect from walrus-client  "http: server gave HTTP response to HTTPS client"

### ISSUE THREAD

**Issue by vargrant** [lukechampine/walrus#8]
I can't connect to the walrus server 

#./walrus -http 127.0.0.1:9999
Listening on 127.0.0.1:9999...

Server must be already sinchronized - becuase I can't see it more in the top of processes - passed near 24 hours.

.#/walrus-cli -a 127.0.0.1:9999 balance
Could not get balance: Get https://127.0.0.1:9999/balance?limbo=true: http: server gave HTTP response to HTTPS client

Before this in the terminal for walrus-cli was exported passphrase from siad wallet.
#export WALRUS_SEED= ....

**Comment by lukechampine** [comment]
`walrus` servers are expected to use HTTPS by default so that your traffic is encrypted. It's safe to run them as HTTP if they aren't exposed to the internet, though.

To avoid this error, you must specify the `http` explicitly:
```
walrus-cli -a http://127.0.0.1:9999 balance
```
